Matrix Creation and Manipulation

○ Create various types of matrices (zero matrix, identity matrix, random matrix).

○ Perform basic matrix operations (addition, subtraction, multiplication).

○ Transpose a matrix and find the determinant and inverse of a matrix.


In [1]:
import numpy as np

In [3]:
# Zero matrix
zero_matrix = np.zeros((3, 3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# Identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Random matrix
random_matrix = np.random.randint(0, 10, size=(3,3))
random_matrix

array([[8, 5, 6],
       [1, 2, 1],
       [9, 1, 8]])

In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [24]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [25]:
#Matrix addition
add_result = A + B
add_result

array([[ 6,  8],
       [10, 12]])

In [27]:
# Matrix subtraction
sub_result = B - A
sub_result

array([[4, 4],
       [4, 4]])

In [28]:
# Matrix multiplication
mul_result = A @ B
mul_result

array([[19, 22],
       [43, 50]])

In [29]:
# Transpose
A_T = A.T
A_T

array([[1, 3],
       [2, 4]])

In [30]:
# Determinant
det_A = np.linalg.det(A)
det_A

np.float64(-2.0000000000000004)

In [31]:
# Inverse
inv_A = np.linalg.inv(A)

print("Inverse of A:\n", inv_A)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Solving Linear Equations

○ Use NumPy to solve a system of linear equations.

○ Implement matrix factorization methods (LU decomposition, QR decomposition).


Example system:

2x+3y=8

3x+4y=11

In [48]:
# Coefficient matrix and constants
coeffs = np.array([[2, 3], [3, 4]])
constants = np.array([8, 11])

In [49]:
solution = np.linalg.solve(coeffs, constants)
solution

array([1., 2.])

In [46]:
# LU Decomposition
from scipy.linalg import lu
P, L, U = lu(coeffs)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

P:
 [[0. 1.]
 [1. 0.]]
L:
 [[1.         0.        ]
 [0.66666667 1.        ]]
U:
 [[3.         4.        ]
 [0.         0.33333333]]


In [47]:
# QR Decomposition
Q, R = np.linalg.qr(coeffs)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]
R:
 [[-3.60555128 -4.99230177]
 [ 0.         -0.2773501 ]]


Eigenvalues and Eigenvectors

○ Calculate the eigenvalues and eigenvectors of a given matrix.

○ Verify the results by reconstructing the original matrix.


In [52]:
matrix = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
eigenvalues, eigenvectors

(array([5., 2.]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

In [53]:
# Reconstruct matrix
D = np.diag(eigenvalues)
V = eigenvectors
reconstructed = V @ D @ np.linalg.inv(V)

print("Original Matrix:\n", matrix)
print("Reconstructed Matrix:\n", reconstructed)

Original Matrix:
 [[4 2]
 [1 3]]
Reconstructed Matrix:
 [[4. 2.]
 [1. 3.]]


Vector Operations

○ Perform basic vector operations (addition, dot product, cross product).

○ Normalize a vector and compute vector norms.


In [54]:
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, -1])
print(v1)
print(v2)

[2 3 4]
[ 1  0 -1]


In [55]:
# Addition
v_add = v1 + v2
v_add

array([3, 3, 3])

In [56]:
# Dot product
dot = np.dot(v1, v2)
dot

np.int64(-2)

In [57]:
# Cross product
cross = np.cross(v1, v2)
cross

array([-3,  6, -3])

In [58]:
# Norm
norm_v1 = np.linalg.norm(v1)
norm_v1

np.float64(5.385164807134504)

In [59]:
# Normalization
v1_normalized = v1 / norm_v1
print("Normalized v1:", v1_normalized)

Normalized v1: [0.37139068 0.55708601 0.74278135]


Matrix Decomposition

○ Understand and implement Principal Component Analysis (PCA) using SVD.

In [2]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [3]:
# Sample data
X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9],
              [1.9, 2.2],
              [3.1, 3.0]])

In [5]:
# Standardize
X_std = StandardScaler().fit_transform(X)

In [6]:
# PCA using SVD
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_std)
X_pca

array([[ 0.5124457 ,  0.23853092],
       [-2.57528445,  0.06114533],
       [ 0.69555387, -0.43434461],
       [-0.1485184 , -0.0800397 ],
       [ 1.51580328,  0.21470806]])

In [8]:
# SVD directly
U, S, Vt = np.linalg.svd(X_std)
print(U)
print(S)
print(Vt)

[[-0.16455164 -0.43419748  0.58500768  0.16077787 -0.64522228]
 [ 0.8269506  -0.11130276  0.46820113  0.00859664  0.29065132]
 [-0.22334958  0.79063685  0.56712958 -0.051828    0.02619621]
 [ 0.0476908   0.14569615 -0.09672794  0.98231635  0.04686701]
 [-0.48674019 -0.39083277  0.32796563  0.08028092  0.70450497]]
[3.11419381 0.54936044]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [9]:
print("PCA Components:\n", pca.components_)
print("Explained Variance:\n", pca.explained_variance_ratio_)


PCA Components:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Explained Variance:
 [0.96982031 0.03017969]


Calculus Tasks

Numerical Differentiation

○ Use NumPy to compute the numerical derivative of a given function.

○ Implement forward, backward, and central difference methods for differentiation.


In [10]:
# Function to differentiate
def f(x):
    return x**2 + 3*x + 2
# Derivative at a point
x = 2.0
h = 1e-5

In [11]:
forward_diff = (f(x + h) - f(x)) / h
backward_diff = (f(x) - f(x - h)) / h
central_diff = (f(x + h) - f(x - h)) / (2 * h)

In [12]:
print("Forward Difference:", forward_diff)
print("Backward Difference:", backward_diff)
print("Central Difference:", central_diff)


Forward Difference: 7.000010000091094
Backward Difference: 6.999990000089439
Central Difference: 7.0000000000902665


Numerical Integration

○ Use NumPy to compute the numerical integral of a given function.

○ Implement the trapezoidal rule and Simpson's rule for integration.


In [16]:
import scipy
print(scipy.__version__)


1.14.1


In [20]:
from scipy.integrate import simpson #, trapz
#from scipy import trapz
#unable to import trapz

# Function
def g(x):
    return x**2 + 1

x_vals = np.linspace(0, 5, 100)
y_vals = g(x_vals)

# Trapezoidal rule
#trapezoid_area = trapz(y_vals, x_vals)

# Simpson’s rule
simpson_area = simpson(y_vals, x=x_vals)


#print("Trapezoidal Area:", trapezoid_area)
print("Simpson's Area:", simpson_area)

Simpson's Area: 46.66666666666667


Partial Derivatives

○ Calculate partial derivatives of multivariable functions using NumPy.

○ Verify results by comparing with analytical solutions.

In [21]:
def func(x, y):
    return x**2 * y + y**3

x0, y0 = 1.0, 2.0
h = 1e-5

# ∂f/∂x
df_dx = (func(x0 + h, y0) - func(x0 - h, y0)) / (2 * h)

# ∂f/∂y
df_dy = (func(x0, y0 + h) - func(x0, y0 - h)) / (2 * h)

print("∂f/∂x:", df_dx)
print("∂f/∂y:", df_dy)

∂f/∂x: 4.000000000026205
∂f/∂y: 13.00000000021839


Optimization

○ Use NumPy to solve optimization problems with constraints.

In [22]:
from scipy.optimize import minimize

# Objective function
def obj(x):
    return x[0]**2 + x[1]**2  # Minimize x² + y²

# Constraint: x + y = 1
cons = ({'type': 'eq', 'fun': lambda x: x[0] + x[1] - 1})

# Initial guess
x0 = [0.5, 0.5]

# Solve
res = minimize(obj, x0, constraints=cons)

print("Optimal values:", res.x)
print("Minimum value:", res.fun)

Optimal values: [0.5 0.5]
Minimum value: 0.5
