In [2]:
import numpy as np

Create a 1D NumPy array containing the integers from 0 to 9.

In [3]:
array_1d = np.arange(10)
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D Array:", array_1d)


1D Array: [0 1 2 3 4 5 6 7 8 9]


Create a 2D NumPy array (3x3) containing random integers between 1 and 20.

In [5]:
array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D Array (3x3) with random integers (1-20):\n", array_2d)

2D Array (3x3) with random integers (1-20):
 [[ 4  5 16]
 [ 6  4  3]
 [ 9 20  3]]


Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

In [8]:
array_3d = np.ones((2, 3, 4))
print("3D Array (2,3,4) filled with ones:\n", array_3d)

3D Array (2,3,4) filled with ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Add two 1D arrays element-wise.

In [9]:
array_1d_a = np.array([1, 2, 3, 4, 5])
array_1d_b = np.array([5, 4, 3, 2, 1])
array_1d_sum = array_1d_a + array_1d_b
print("Element-wise sum of two 1D arrays:", array_1d_sum)

Element-wise sum of two 1D arrays: [6 6 6 6 6]


Multiply two 2D arrays element-wise.

In [12]:
array_2d_a = np.random.randint(1, 10, size=(3, 3))
array_2d_b = np.random.randint(1, 10, size=(3, 3))
array_2d_product = array_2d_a * array_2d_b
print(array_2d_a)
print(array_2d_b)
print("Element-wise product of two 2D arrays:\n", array_2d_product)

[[3 8 7]
 [6 4 1]
 [8 4 6]]
[[2 1 3]
 [8 7 8]
 [3 8 5]]
Element-wise product of two 2D arrays:
 [[ 6  8 21]
 [48 28  8]
 [24 32 30]]


Calculate the dot product of two matrices.

In [13]:
dot_product = np.dot(array_2d_a, array_2d_b)
print("Dot product of two matrices:\n", dot_product)

Dot product of two matrices:
 [[ 91 115 108]
 [ 47  42  55]
 [ 66  84  86]]


Calculate the mean, median, and standard deviation of a 1D array.


In [16]:
array_1d = np.array([10, 20, 30, 40, 40, 50, 60])
mean_1d = np.mean(array_1d)
median_1d = np.median(array_1d)
std_dev_1d = np.std(array_1d)

In [17]:
print(mean_1d)
print(median_1d)
print(std_dev_1d)

35.714285714285715
40.0
15.90789817951435


Find the maximum and minimum values in a 2D array.

In [18]:
array_2d = np.random.randint(1, 100, size=(3, 3))
max_2d = np.max(array_2d)
min_2d = np.min(array_2d)

print("2D Array:\n", array_2d)
print("Max value in 2D array:", max_2d)
print("Min value in 2D array:", min_2d)

2D Array:
 [[65 80 33]
 [44 89 82]
 [48 65  3]]
Max value in 2D array: 89
Min value in 2D array: 3


Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.

In [20]:
normal_dist_array = np.random.normal(0, 1, 1000)

print("First 10 values from normal distribution array:", normal_dist_array[:10])

First 10 values from normal distribution array: [-2.47299392  0.75003849 -0.50445528  0.54777461  1.2067585  -0.3178241
  0.58380911 -2.01500329  0.00431085  0.58064276]


Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.

In [22]:
uniform_array = np.random.randint(10, 51, size=(5, 5))
print("2D Array (5x5) with random integers (10-50):\n", uniform_array)

2D Array (5x5) with random integers (10-50):
 [[18 13 21 45 46]
 [15 25 20 38 22]
 [24 44 50 40 15]
 [43 12 28 27 16]
 [42 39 37 31 28]]


Calculate the cumulative sum of a 1D array.

In [24]:
array_1d = np.array([1, 2, 4, 3, 10])
cumsum_1d = np.cumsum(array_1d)
print("Cumulative sum of 1D array:", cumsum_1d)

Cumulative sum of 1D array: [ 1  3  7 10 20]


Compute the correlation coefficient matrix of a 2D array.

In [26]:
array_2d = np.random.randint(1, 100, size=(3, 3))
correlation_matrix = np.corrcoef(array_2d)
print("2D Array:\n", array_2d)
print("Correlation coefficient matrix:\n", correlation_matrix)

2D Array:
 [[24 34 92]
 [19 95 49]
 [55 88 53]]
Correlation coefficient matrix:
 [[ 1.          0.01565343 -0.42402883]
 [ 0.01565343  1.          0.89890022]
 [-0.42402883  0.89890022  1.        ]]


Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

In [28]:
die_rolls = np.random.randint(1, 7, size=1000)
roll_frequencies = np.bincount(die_rolls, minlength=7)[1:]  # Ignoring the zero index

print("Frequencies of rolling a six-sided die 1000 times:", roll_frequencies)

Frequencies of rolling a six-sided die 1000 times: [162 146 166 176 172 178]
