Indexing and Slicing

 Task 1: Extract a 3x3 sub-array from a (5,5) array starting at (1,1)

In [2]:
import numpy as np

In [8]:
array_2d = np.arange(25).reshape(5, 5)
sub_array = array_2d[:3, :3]  # Extracting a 3x3 sub-array
print("3x3 Sub-array:\n", sub_array)

3x3 Sub-array:
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


Task 2: Extract first two rows and all columns from the second slice of a (4,3,2) array

In [17]:
array_3d = np.arange(24).reshape(4, 3, 2)
sub_array_3d = array_3d[:2, :, 1]  # Selecting first two rows, all columns, second slice
print("\nExtracted elements from 3D array:\n",sub_array_3d)


Extracted elements from 3D array:
 [[ 1  3  5]
 [ 7  9 11]]


Task 3: Fancy indexing to extract elements at positions [1, 3, 4, 7] from a 1D array

In [19]:
array_1d = np.arange(11,20)  # Example 1D array
indices = [1, 3, 4, 7]
fancy_selected = array_1d[indices]
print("\nFancy Indexed Elements:\n", fancy_selected)


Fancy Indexed Elements:
 [12 14 15 18]


Task 4: Fancy indexing to select rows [0, 2, 3] and columns [1, 3] from a 2D array

In [24]:
array_2d_fancy = np.arange(25).reshape(5, 5)
rows = [0, 2, 3]
cols = [1, 3]
fancy_selected_2d = array_2d_fancy[np.ix_(rows, cols)]
print("\nFancy Indexed 2D Array:\n", fancy_selected_2d)


Fancy Indexed 2D Array:
 [[ 1  3]
 [11 13]
 [16 18]]


Task 5: Extract all elements greater than 10 from a random 1D array

In [26]:
random_array = np.random.randint(1, 20, size=15)
greater_than_10 = random_array[random_array > 10]
print("\nElements greater than 10:\n", greater_than_10)


Elements greater than 10:
 [17 15 18 15 15 19 18]


Task 6: Replace all elements greater than 15 with 0 in a (5,5) array

In [32]:
array = np.random.randint(1, 30, size=10)
print(array)
array[array>15] = 0
print(array)

[23  8 13  5 13 21  6 12 24 20]
[ 0  8 13  5 13  0  6 12  0  0]


Broadcasting


Task 1: Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3)

In [33]:
array_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9],
                      [10, 11, 12]])
array_1d = np.array([10, 20, 30])  # Shape (3,)

result1 = array_2d + array_1d  # Broadcasting occurs
print("Result 1 (Adding 1D array to each row of 2D array):\n", result1)

Result 1 (Adding 1D array to each row of 2D array):
 [[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]



Task 2: Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)

In [34]:
array_2d_mul = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
array_1d_mul = np.array([1, 2, 3])  # Shape (3,)

result2 = array_2d_mul * array_1d_mul  # Broadcasting occurs
print("\nResult 2 (Multiplying 2D array by 1D array):\n", result2)


Result 2 (Multiplying 2D array by 1D array):
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


Task 3: Create two 2D arrays of shapes (3, 1) and (1, 4) and perform element-wise addition

In [35]:
array_2d_3x1 = np.array([[1], [2], [3]])  # Shape (3,1)
array_2d_1x4 = np.array([[10, 20, 30, 40]])  # Shape (1,4)

result3 = array_2d_3x1 + array_2d_1x4  # Broadcasting occurs
print("\nResult 3 (Element-wise addition of (3,1) and (1,4)):\n", result3)


Result 3 (Element-wise addition of (3,1) and (1,4)):
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


Task 4: Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along axis 0

In [36]:
array_3d = np.arange(24).reshape(2, 3, 4)  # Shape (2, 3, 4)
array_2d_add = np.array([[1, 1, 1, 1],
                          [2, 2, 2, 2],
                          [3, 3, 3, 3]])  # Shape (3, 4)

result4 = array_3d + array_2d_add  # Broadcasting occurs
print("\nResult 4 (Adding 2D array to each slice of 3D array):\n", result4)


Result 4 (Adding 2D array to each slice of 3D array):
 [[[ 1  2  3  4]
  [ 6  7  8  9]
  [11 12 13 14]]

 [[13 14 15 16]
  [18 19 20 21]
  [23 24 25 26]]]


Some More

Task 1: Extract every second row and column, then add a 1D array to each row

In [39]:
array_2d = np.arange(25).reshape(5, 5)  # Creating a (5,5) array
sliced_array = array_2d[::2, ::2]  # Extract every second row and column
array_1d = np.array([10, 20, 30])  # Shape (3,)
result1 = sliced_array + array_1d  # Broadcasting
print(array_2d)
print(sliced_array)
print("Result 1 (Sliced and Added 1D array to each row):\n", result1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  2  4]
 [10 12 14]
 [20 22 24]]
Result 1 (Sliced and Added 1D array to each row):
 [[10 22 34]
 [20 32 44]
 [30 42 54]]


Task 2: Extract a sub-array from a 3D array and subtract a 2D array from each slice along the third axis

In [40]:
array_3d = np.arange(24).reshape(4, 3, 2)  # Shape (4,3,2)
sub_array_3d = array_3d[:2, :, :]  # Extract first two blocks (shape: 2,3,2)
array_2d = np.array([[1, 2], [3, 4], [5, 6]])  # Shape (3,2)
result2 = sub_array_3d - array_2d  # Broadcasting
print("\nResult 2 (Subtracted 2D array from each slice):\n", result2)


Result 2 (Subtracted 2D array from each slice):
 [[[-1 -1]
  [-1 -1]
  [-1 -1]]

 [[ 5  5]
  [ 5  5]
  [ 5  5]]]


Task 3: Extract diagonal elements and create a 1D array

In [41]:
array_diag = np.arange(16).reshape(4, 4)  # Creating a (4,4) matrix
diagonal_elements = np.diag(array_diag)  # Extract diagonal
print("\nResult 3 (Diagonal Elements as 1D array):\n", diagonal_elements)


Result 3 (Diagonal Elements as 1D array):
 [ 0  5 10 15]


Task 4: Reverse the order of elements in each row of a 2D array

In [42]:
array_reverse = np.arange(20).reshape(4, 5)  # Creating a (4,5) matrix
reversed_rows = array_reverse[:, ::-1]  # Reverse elements in each row
print(array_reverse)
print("\nResult 4 (Rows Reversed):\n", reversed_rows)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Result 4 (Rows Reversed):
 [[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


Task 5: Extract a sub-array from a 3D array and add a 1D array to each row along the third axis

In [43]:
array_3d_large = np.arange(4*5*6).reshape(4, 5, 6)  # Shape (4,5,6)
sub_array_3d_large = array_3d_large[:2, :3, :4]  # Extract shape (2,3,4)
array_1d_broadcast = np.array([10, 20, 30, 40])  # Shape (4,)
result5 = sub_array_3d_large + array_1d_broadcast  # Broadcasting
print("\nResult 5 (Sub-array with 1D array added along third axis):\n", result5)


Result 5 (Sub-array with 1D array added along third axis):
 [[[10 21 32 43]
  [16 27 38 49]
  [22 33 44 55]]

 [[40 51 62 73]
  [46 57 68 79]
  [52 63 74 85]]]


Task 6: Set last column to the sum of the first two columns for each row

In [46]:
array_2d_sum = np.random.randint(1, 10, size=(4, 4))  # Random (4,4) array
print(array_2d_sum)
array_2d_sum[:, -1] = array_2d_sum[:, 0] + array_2d_sum[:, 1]  # Last column = sum of first two columns
print("\nResult 6 (Last column set to sum of first two columns):\n", array_2d_sum)

[[2 4 9 4]
 [3 3 6 7]
 [5 9 7 7]
 [1 7 6 8]]

Result 6 (Last column set to sum of first two columns):
 [[ 2  4  9  6]
 [ 3  3  6  6]
 [ 5  9  7 14]
 [ 1  7  6  8]]


For serial 16 to last:


Indexing and Slicing


Task 7: Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).

In [3]:
array_2d = np.arange(36).reshape(6, 6)  # Creating a (6,6) array
sub_array_2d = array_2d[1:3, 1:3]  # Extracting a 2x2 sub-array from (1,1)
print("Result 1 (Extracted 2x2 sub-array):\n", sub_array_2d)

Result 1 (Extracted 2x2 sub-array):
 [[ 7  8]
 [13 14]]


Task 8: Extract all elements in the first two rows and all columns of the second slice (third axis) from (3,2,1) array

In [7]:
array_3d = np.arange(6).reshape(3, 2, 1)  # Creating a (3,2,1) array
sub_array_3d = array_3d[:2, :, 0]  # Extract first two rows, all columns of the second slice
print(array_3d)
print("\nResult 2 (Extracted elements from 3D array):\n", sub_array_3d)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]

Result 2 (Extracted elements from 3D array):
 [[0 1]
 [2 3]]


Task 9: Use fancy indexing to extract elements at positions [1, 3, 4, 6] from a 1D array

In [8]:
array_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80])  # Example 1D array
indices = [1, 3, 4, 6]
extracted_elements = array_1d[indices]  # Fancy indexing
print("\nResult 3 (Extracted elements using fancy indexing):\n", extracted_elements)


Result 3 (Extracted elements using fancy indexing):
 [20 40 50 70]


Task 10: Use fancy indexing to select rows [0, 2, 2] and columns [1, 3] in a 2D array

In [11]:
array_2d_fancy = np.arange(36).reshape(6, 6)  # Creating a (6,6) array
rows = [0, 2, 2]
cols = [1, 3, 4]
selected_elements = array_2d_fancy[rows, cols]  # Fancy indexing
print("\nResult 4 (Selected elements using fancy indexing):\n", selected_elements)


Result 4 (Selected elements using fancy indexing):
 [ 1 15 16]


Task 11: Extract all elements greater than 8 from a 1D array

In [14]:
array_random = np.random.randint(1, 15, size=10)  # Random array of integers
filtered_elements = array_random[array_random > 8]  # Boolean indexing
print(array_random)
print("\nResult 5 (Elements greater than 8):\n", filtered_elements)

[ 4  3  1  8  6  5  5  1  5 14]

Result 5 (Elements greater than 8):
 [14]


Task 12: Replace all elements greater than 13 with 0 in a (6,6) array

In [16]:
array_2d_replace = np.random.randint(5, 20, size=(6, 6))  # Creating a (6,6) random array
array_2d_replace[array_2d_replace > 13] = 0  # Replacing elements greater than 13 with 0
print("\nResult 6 (Replaced elements > 13 with 0):\n", array_2d_replace)


Result 6 (Replaced elements > 13 with 0):
 [[ 9  5 11  0 13  0]
 [10 13  9  0  0  7]
 [ 0  6  0 11  0  7]
 [ 0  0  0  8  9  8]
 [11 12  0  0  0  0]
 [12  0  6  0  0  0]]
